[jenkins]
jenkins-server ansible_host=13.233.64.163

[kubernetes_master]
master ansible_host=35.154.57.254

[kubernetes_workers]
worker1 ansible_host=15.207.116.106
worker2 ansible_host=13.233.121.79

[kubernetes:children]
kubernetes_master
kubernetes_workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/root/.ssh/project.pem
ansible_python_interpreter=/usr/bin/python3
