apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: devops-dashboard
  namespace: devops-dashboard

spec:
  selector:
    matchLabels:
      app: devops-dashboard

  namespaceSelector:
    matchNames:
      - devops-dashboard

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
