---
- name: Check if worker has already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Read join command from master
  delegate_to: master
  slurp:
    src: /tmp/kubeadm_join_command
  register: join_cmd
  run_once: true

- name: Join worker to cluster
  command: "{{ join_cmd.content | b64decode }}"
  when: not kubelet_conf.stat.exists
# tasks file for workers
